### ISSUE TITLE
Sitemap Icons aren't centered 

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2-module-icingadb#288]
## Describe the bug
The sitemap icons are still displayed crooked on my end.

<img width="1266" alt="Bildschirmfoto 2021-08-26 um 10 24 49" src="https://user-images.githubusercontent.com/57616252/130928856-da76f9e8-9c16-451b-8b5a-b74bfc72ac85.png">

**Comment by flourish86** [comment]
This also applies to the User Balls.

![Screen Shot 2021-08-30 at 14 54 37](https://user-images.githubusercontent.com/6977434/131342170-a6f2c640-57f8-426c-a2cd-0dcadb2b39e2.png)

**Comment by nilmerg** [comment]
I've wanted to fix this now, but failed. I cannot reproduce that. Not with Chromium, Chrome or Firefox. Not on 1440p nor on 1080p. Not with any zoom factor between 80% and 200%.

The only thing I can notice is that some icons (the sitemap especially) are not vertically centered. This is probably due to the different layouts of the icons themselves. The check icon doesn't have this problem for example:

![Screenshot from 2021-09-01 16-13-18](https://user-images.githubusercontent.com/16668527/131687312-0f542f42-b4f0-4818-8ec9-08ff9af2d25d.png)

But this can only be solved by fine-tuning the line-height for every single icon we use in state balls. But this should be done by someone who can perfectly reproduce what is shown in the OP, otherwise I fear the horizontal dis-alignment stays if **I** do that.
